module.exports = Object.freeze({
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  DLQ_CREATED: 'DLQ_CREATED',
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_STATUS_CHANGED: 'APPOINTMENT_STATUS_CHANGED',
});
